resource "tls_private_key" "shop" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "terraform_generated" {
  key_name   = "tf-shop-generated-key"
  public_key = tls_private_key.shop.public_key_openssh

  tags = local.common_tags
}

output "private_key" {
  description = "Private RSA key generated by Terraform"
  value       = tls_private_key.shop.private_key_pem
  sensitive   = true
}
